name: compsoc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.7.1
  - scikit-learn=1.3.0
  - numpy=1.24.3
  - scipy=1.10.1
  - pandas=1.5.3
  - networkx=3.1
  - graph-tool=2.57
  - powerlaw=1.4.6