name: compsoc
channels:
  - conda-forge
dependencies:
  - python=3.11.15
  - graph-tool=2.98
  - jupyterlab=4.5.6
  - matplotlib=3.10.9
  - numpy=2.4.3
  - pandas=3.0.2
  - pip=26.0.1
  - scikit-learn=1.8.0
  - scipy=1.17.1
  - pip:
    - powerlaw==2.0.0
