name: compsoc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - matplotlib=3.7.2
  - scikit-learn=1.2.2
  - numpy=1.25.2
  - scipy=1.11.1
  - pandas=2.03
  - networkx=3.1
  - graph-tool=2.58
  - powerlaw=1.4.4
