name: compsoc_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.3
  - matplotlib=3.2.2
  - scikit-learn=0.23.1
  - numpy=1.18.5
  - scipy=1.5.0
  - pandas=1.0.5
  - networkx=2.4
  - graph-tool=2.43
  - pip=20.1.1
  - pip:
    - powerlaw
    - python-louvain